// export const API_URL = "http://localhost:8080"
export const API_URL = process.env.REACT_APP_BASE_URL;
export const IMAGE_FOLDER = `${API_URL}/images/product/`
export const ICON_FOLDER = `${API_URL}/images`
// export const API_URL_WEB = "https://shielded-sea-59884.herokuapp.com"

// GET & SEARCH PRODUCT
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST"
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS"
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST"
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS"

// Product
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS"
export const GET_ALL_CLOTHES_SUCCESS = "GET_ALL_CLOTHES_SUCCESS"
export const GET_ALL_LAPTOP_SUCCESS = "GET_ALL_LAPTOP_SUCCESS"
export const GET_ALL_PHONE_SUCCESS = "GET_ALL_PHONES_SUCCESS"
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS"

// CART
export const GET_ALL_ITEM_IN_CART = "GET_ALL_ITEM_IN_CART"
export const GET_ALL_ITEM_IN_CART_SELECTED = "GET_ALL_ITEM_IN_CART_SELECTED"
export const GET_CART_INFO = "GET_CART_INFO"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_ITEM_IN_CART = "DELETE_ITEM_IN_CART"
export const UPDATE_ITEM_IN_CART = "UPDATE_ITEM_IN_CART"
export const CART_COMPLETE = "CART_COMPLETE"

// AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';

// CATEGORY
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

// COMMENT
export const ADD_COMMENT = "ADD_COMMENT"
export const GET_ALL_COMMENT = "GET_ALL_COMMENT"
export const GET_ALL_COMMENT_BY_PRODUCT = "GET_ALL_COMMENT_BY_PRODUCT"

// ADMIN
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

